config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  	resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end 

	def new
		@product = Product.new
	end 

	def create 
		Product.create(product_params)
		redirect_to root_path
	end 

private 

	def product_params
		params.require(:product).permit(:product_name)
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grocery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<br />
<div class= "container col-9">
	<div class= "row">
		<h1>List of Products</h1>
	</div>

	<div class= "row">
		<% @products.each do |list| %>
		<%= list.product_name %>
		<br />
		<% end %>
	</div>

	<br />
	<div class= "row">
		<%= link_to 'Add a Product', new_product_path, class: 'btn btn-primary' %>
	</div>
</div>

app/views/products/new.html.erb
<br />
<div class= "container col-9">
	<div class= "row">
		<h1>Add a Product</h1>
	</div>
	<div class= "row">
		<%= simple_form_for  @product do |f| %>
			<%= f.input :product_name %>
			<%= f.submit 'Add to List', class: 'btn btn-primary' %>
		<% end %>
	</div>
</div>